export const US_STATES = [
  { name: 'Alabama', abbreviation: 'AL', filingFee: 200 },
  { name: 'Alaska', abbreviation: 'AK', filingFee: 250 },
  { name: 'Arizona', abbreviation: 'AZ', filingFee: 50 },
  { name: 'Arkansas', abbreviation: 'AR', filingFee: 45 },
  { name: 'California', abbreviation: 'CA', filingFee: 70 },
  { name: 'Colorado', abbreviation: 'CO', filingFee: 50 },
  { name: 'Connecticut', abbreviation: 'CT', filingFee: 120 },
  { name: 'Delaware', abbreviation: 'DE', filingFee: 90 },
  { name: 'Florida', abbreviation: 'FL', filingFee: 125 },
  { name: 'Georgia', abbreviation: 'GA', filingFee: 100 },
  { name: 'Hawaii', abbreviation: 'HI', filingFee: 50 },
  { name: 'Idaho', abbreviation: 'ID', filingFee: 100 },
  { name: 'Illinois', abbreviation: 'IL', filingFee: 150 },
  { name: 'Indiana', abbreviation: 'IN', filingFee: 95 },
  { name: 'Iowa', abbreviation: 'IA', filingFee: 50 },
  { name: 'Kansas', abbreviation: 'KS', filingFee: 160 },
  { name: 'Kentucky', abbreviation: 'KY', filingFee: 40 },
  { name: 'Louisiana', abbreviation: 'LA', filingFee: 100 },
  { name: 'Maine', abbreviation: 'ME', filingFee: 175 },
  { name: 'Maryland', abbreviation: 'MD', filingFee: 100 },
  { name: 'Massachusetts', abbreviation: 'MA', filingFee: 500 },
  { name: 'Michigan', abbreviation: 'MI', filingFee: 50 },
  { name: 'Minnesota', abbreviation: 'MN', filingFee: 155 },
  { name: 'Mississippi', abbreviation: 'MS', filingFee: 50 },
  { name: 'Missouri', abbreviation: 'MO', filingFee: 50 },
  { name: 'Montana', abbreviation: 'MT', filingFee: 35 },
  { name: 'Nebraska', abbreviation: 'NE', filingFee: 100 },
  { name: 'Nevada', abbreviation: 'NV', filingFee: 75 },
  { name: 'New Hampshire', abbreviation: 'NH', filingFee: 100 },
  { name: 'New Jersey', abbreviation: 'NJ', filingFee: 125 },
  { name: 'New Mexico', abbreviation: 'NM', filingFee: 50 },
  { name: 'New York', abbreviation: 'NY', filingFee: 200 },
  { name: 'North Carolina', abbreviation: 'NC', filingFee: 125 },
  { name: 'North Dakota', abbreviation: 'ND', filingFee: 135 },
  { name: 'Ohio', abbreviation: 'OH', filingFee: 99 },
  { name: 'Oklahoma', abbreviation: 'OK', filingFee: 100 },
  { name: 'Oregon', abbreviation: 'OR', filingFee: 100 },
  { name: 'Pennsylvania', abbreviation: 'PA', filingFee: 125 },
  { name: 'Rhode Island', abbreviation: 'RI', filingFee: 150 },
  { name: 'South Carolina', abbreviation: 'SC', filingFee: 110 },
  { name: 'South Dakota', abbreviation: 'SD', filingFee: 150 },
  { name: 'Tennessee', abbreviation: 'TN', filingFee: 300 },
  { name: 'Texas', abbreviation: 'TX', filingFee: 300 },
  { name: 'Utah', abbreviation: 'UT', filingFee: 54 },
  { name: 'Vermont', abbreviation: 'VT', filingFee: 125 },
  { name: 'Virginia', abbreviation: 'VA', filingFee: 100 },
  { name: 'Washington', abbreviation: 'WA', filingFee: 180 },
  { name: 'Washington DC', abbreviation: 'DC', filingFee: 99 },
  { name: 'West Virginia', abbreviation: 'WV', filingFee: 100 },
  { name: 'Wisconsin', abbreviation: 'WI', filingFee: 130 },
  { name: 'Wyoming', abbreviation: 'WY', filingFee: 100 },
];

export const BUSINESS_CATEGORIES = [
  'Technology & Software',
  'E-commerce & Retail',
  'Consulting & Professional Services',
  'Marketing & Advertising',
  'Finance & Accounting',
  'Real Estate',
  'Healthcare & Wellness',
  'Education & Training',
  'Media & Entertainment',
  'Food & Beverage',
  'Construction & Trades',
  'Import & Export',
  'Travel & Hospitality',
  'Legal Services',
  'Manufacturing',
  'Non-profit & Social Enterprise',
  'Other'
];
export const ADDONS = [
  {
    id: 'itin',
    title: 'ITIN Application',
    price: 150,
    priceLabel: '$150 one-time',
    icon: 'identification',
    bullets: [
      'Individual Taxpayer Identification Number',
      'Required for non-US members to open bank accounts',
      'We handle the full IRS application process',
      'Typical processing: 6–10 weeks',
    ],
  },
  {
    id: 'us_phone',
    title: 'US Phone Number',
    price: 10,
    priceLabel: '$10/month',
    icon: 'phone',
    bullets: [
      'US virtual phone number with your area code',
      'Forward calls to any international number',
      'Voicemail + SMS included',
      'Gives your business a local US presence',
    ],
  },
  {
    id: 'vps',
    title: 'VPS Hosting',
    price: 20,
    priceLabel: '$20/month',
    icon: 'server',
    bullets: [
      'Virtual Private Server hosted in the US',
      'Ideal for running business applications',
      '99.9% uptime SLA',
      'Managed setup assistance included',
    ],
  },
  {
    id: 'trading_address',
    title: 'US Trading Address',
    price: 25,
    priceLabel: '$25/month',
    icon: 'map-pin',
    bullets: [
      'Professional US business mailing address',
      'Mail scanning and forwarding',
      'Use on your website, invoices, and contracts',
      'Available in multiple US cities',
    ],
  },
  {
    id: 'wise_setup',
    title: 'Wise Business Account Setup',
    price: 80,
    priceLabel: '$80 one-time',
    icon: 'credit-card',
    bullets: [
      'We guide you through Wise account setup',
      'Multi-currency business account',
      'Accept USD, EUR, GBP and more',
      'Faster and cheaper international transfers',
    ],
  },
];

export const PACKAGES = {
  standard: { label: 'Standard Package', price: 120 },
  advanced: { label: 'Advanced Package', price: 170 },
} as const;
